vich_uploader:
  db_driver: orm

  mappings:
    regime_image:
      uri_prefix: /admin/img
      upload_destination: "%kernel.project_dir%/public/admin/img/regime"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
