<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7JnxcEQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7JnxcEQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7JnxcEQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7JnxcEQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7JnxcEQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7JnxcEQ',
    'container.build_id' => '65a1aa7a',
    'container.build_time' => 1621301450,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7JnxcEQ');
