<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membre extends \App\Entity\Membre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'datee', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'poids', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'idRegime'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'datee', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'poids', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Membre' . "\0" . 'idRegime'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCin(int $cin): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCin();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatee', []);

        return parent::getDatee();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatee(\DateTimeInterface $datee): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatee', [$datee]);

        return parent::setDatee($datee);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille(float $taille): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoids(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoids', []);

        return parent::getPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoids(float $poids): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoids', [$poids]);

        return parent::setPoids($poids);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(int $telephone): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRegime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRegime', []);

        return parent::getIdRegime();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRegime($idRegime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRegime', [$idRegime]);

        return parent::setIdRegime($idRegime);
    }

    /**
     * {@inheritDoc}
     */
    public function addIdRegime(\App\Entity\Regime $idRegime): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdRegime', [$idRegime]);

        return parent::addIdRegime($idRegime);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdRegime(\App\Entity\Regime $idRegime): \App\Entity\Membre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdRegime', [$idRegime]);

        return parent::removeIdRegime($idRegime);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

}
